In [3]:
import pandas as pd
import datetime as dt

## Data constraints and ranges

Problem: There is movie rating data range between 1-5 if its above 6 then the data analysis cannot be accurate
Solution: If the rating is above 6 then convert into 5

In [4]:
data = {
    "movie": [
        "The Shawshank Redemption",
        "The Dark Knight",
        "Inception",
        "Interstellar",
        "Pulp Fiction",
        "Fight Club",
        "Forrest Gump",
        "The Matrix",
        "Goodfellas",
        "Parasite",
        "Gladiator",
        "The Lord of the Rings",
        "Titanic",
        "Avatar",
        "The Avengers",
        "Whiplash",
        "The Prestige",
        "The Departed",
        "The Lion King",
        "Gladiator II"
    ],
    "rating": [8, 8, 7, 7, 6, 6, 5, 5, 4, 3, 7, 8, 4, 3, 6, 5, 7, 6, 5, 4]
}
df = pd.DataFrame(data)
df.head(5)

                      movie  rating
0  The Shawshank Redemption       8
1           The Dark Knight       8
2                 Inception       7
3              Interstellar       7
4              Pulp Fiction       6

In [5]:
df.dtypes

movie     object
rating     int64
dtype: object

In [6]:
# Converting the rating above 5 to 5

df.loc[df["rating"] > 5, "rating"] = 5
df

                       movie  rating
0   The Shawshank Redemption       5
1            The Dark Knight       5
2                  Inception       5
3               Interstellar       5
4               Pulp Fiction       5
5                 Fight Club       5
6               Forrest Gump       5
7                 The Matrix       5
8                 Goodfellas       4
9                   Parasite       3
10                 Gladiator       5
11     The Lord of the Rings       5
12                   Titanic       4
13                    Avatar       3
14              The Avengers       5
15                  Whiplash       5
16              The Prestige       5
17              The Departed       5
18             The Lion King       5
19              Gladiator II       4

In [7]:
df['rating'].astype('int')
stats = df.describe(include='all')

In [8]:
stats

                           movie    rating
count                         20  20.00000
unique                        20       NaN
top     The Shawshank Redemption       NaN
freq                           1       NaN
mean                         NaN   4.65000
std                          NaN   0.67082
min                          NaN   3.00000
25%                          NaN   4.75000
50%                          NaN   5.00000
75%                          NaN   5.00000
max                          NaN   5.00000

## Dates

In [9]:
users = {
    "user_name":["Raj","John","Kishore","Paul"],
    "subscription_date":["6/12/2023","1/15/2021","5/5/2028","5/25/2027"]
}
df = pd.DataFrame(users)
df.head()

  user_name subscription_date
0       Raj         6/12/2023
1      John         1/15/2021
2   Kishore          5/5/2028
3      Paul         5/25/2027

In [10]:
df.dtypes

user_name            object
subscription_date    object
dtype: object

In [11]:
# Convert subscription_date to date formate
df['subscription_date'] = pd.to_datetime(df['subscription_date']).dt.date
df.head()

  user_name subscription_date
0       Raj        2023-06-12
1      John        2021-01-15
2   Kishore        2028-05-05
3      Paul        2027-05-25

In [12]:
# convert subscription_date to todays date
today = dt.date.today()
df.loc[df['subscription_date'] > today, "subscription_date"] = today
df

  user_name subscription_date
0       Raj        2023-06-12
1      John        2021-01-15
2   Kishore        2026-10-07
3      Paul        2026-10-07